---
hostPort: localhost:5555
#username: username
#password: password

rules:
- pattern: metrics<name=zookeeper[.]([^.]+)[.]([^.]+)><>([^:]+)
  name: onyx_zookeeper_$1_$2_$3
- pattern: metrics<name=peer[.]([^.]+)[.]([^.]+)><>([^:]+)
  name: onyx_peer_event
  labels:
    event-type: "$1"
- pattern: metrics<name=group[.]([^.]+)[.]([^.]+)><>([^:]+)
  name: onyx_group_event
  labels:
    event-type: "$1"
- pattern: metrics<name=([^.]+)[.]([^.]+)[.]([^.]+)><>([^:]+)
  name: onyx_jobs_$3_$4
  labels:
    job: "$1"
    task: "$2"
